services:
  ftp:
    build: .
    ports:
      - 21:21
      - 20:20
      - 1024-1048:1024-1048
    volumes:
      - "/home/mchost/servers/7fb39116-f6cb-4e75-bc59-7efefe7cbc84:/data"
    env_file:
      - .env
    networks:
      - the-untitled-cloud-api_dev-database

networks:
  the-untitled-cloud-api_dev-database:
    external: true