version: "3"
services:
  mc_host_api:
    build: mc-host-api
    hostname: api
    expose:
      - 8080
    environment:
      STRIPE_API_KEY: ${STRIPE_SK}
      STRIPE_API_ENDPOINT_SECRET: ${STRIPE_WHOOK}
      DOCKER_HOST: "unix:///var/run/docker.sock"
      DATABASE_URL: "jdbc:postgresql://database:5432/${DATABASE_NAME}"
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL}
      SMTP_FROM_NAME: ${SMTP_FROM_NAME}
      JWT_SECRET: ${JWT_SECRET}
      SALT: ${SALT}
      PEPPER: ${PEPPER}
      CONTAINER_DIRECTORY: ${CONTAINER_DIRECTORY}
      DOCKER_TLS_VERIFY: 0
      TOKEN: ${TOKEN}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    networks:
      mc_host_network:
    depends_on:
      - mc_host_database

  mc_host_database:
    image: postgres:latest
    hostname: database
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - "${DATABASE_VOLUME}:/var/lib/postgresql/data"
    expose:
      - 5432
#    ports:
#      - "5444:5432"
    networks:
      mc_host_network:
      internal:

  mc_host_ftp:
    build: mc-host-ftp
    environment:
      PGHOST: database
      PGUSER: ${DATABASE_USER}
      PGPASSWORD: ${DATABASE_PASS}
      PGDATABASE: ${DATABASE_NAME}
      PGPORT: 5432
      SALT: ${SALT}
      PEPPER: ${PEPPER}
    volumes:
      - "${CONTAINER_DIRECTORY}:/servers"
    ports:
      - "21:21"
    networks:
      mc_host_network:
    depends_on:
      - mc_host_database

  mc_host_front:
    build:
      context: mc-host-front
      dockerfile: Dockerfile
      args:
        VITE_STRIPE_PUBLIC_KEY: ${STRIPE_PK}
        VITE_API_BASE_URL: ${API_ENDPOINT}
        VITE_API_WS_URL: ${WS_ENDPOINT}
    hostname: front
    volumes:
      - "./nginx:/etc/nginx:ro"
    ports:
      - "${PORT}:80"
    networks:
      mc_host_network:
    depends_on:
      - mc_host_api

networks:
  mc_host_network:
  internal:
    driver: bridge
    internal: true
