version: "3"
services:
  mc_host_api:
    build: api
    hostname: api
    expose:
      - 8080
    environment:
      STRIPE_API_KEY: ${STRIPE_SK}
      STRIPE_API_ENDPOINT_SECRET: ${STRIPE_WHOOK}
      DOCKER_HOST: "unix:///var/run/docker.sock"
      DATABASE_URL: "jdbc:postgresql://database:5432/${DATABASE_NAME}"
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL}
      SMTP_FROM_NAME: ${SMTP_FROM_NAME}
      JWT_SECRET: ${JWT_SECRET}
      SALT: ${SALT}
      PEPPER: ${PEPPER}
      CONTAINER_DIRECTORY: ${CONTAINER_DIRECTORY}
      DOCKER_TLS_VERIFY: 0
      TOKEN: ${TOKEN}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    networks:
      mc_host_network:
    depends_on:
      - mc_host_database

  mc_host_database:
    image: postgres:latest
    hostname: database
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - "${DATABASE_VOLUME}:/var/lib/postgresql/data"
    expose:
      - 5432
    networks:
      mc_host_network:
      internal:

  mc_host_ftp:
    build: ftp
    environment:
      DATABASE: ${DATABASE_NAME}
      TABLE: subscription_item
      HOST: database
      PORT: 5432
      USERNAME: ${DATABASE_USER}
      PASSWORD: ${DATABASE_PASS}
      USERNAME_COLUMN: id
      PWD_COLUMN: ftp_password
      PW_TYPE: md5
      PASV_ADDRESS: ${PUBLIC_ADDRESS}
    volumes:
      - "${CONTAINER_DIRECTORY}:/data"
    ports:
      - "20-21:20-21"
      - "989-990:989-990"
      - "1024-1048:1024-1048"
    networks:
      mc_host_network:
    depends_on:
      - mc_host_database

  mc_host_front:
    build:
      context: front
      dockerfile: Dockerfile
      args:
        VITE_STRIPE_PUBLIC_KEY: ${STRIPE_PK}
        VITE_API_BASE_URL: ${API_ENDPOINT}
        VITE_API_WS_URL: ${WS_ENDPOINT}
        VITe_FTP_BASE_URL: ${FTP_BASE_URL}
        VITE_SERVER_ADDRESS: ${PUBLIC_ADDRESS}
    hostname: front
    volumes:
      - "./nginx:/etc/nginx:ro"
    ports:
      - "${PORT}:80"
    networks:
      mc_host_network:
    depends_on:
      - mc_host_api
      - web-ftp

  web-ftp:
    build:
      context: web-ftp
      dockerfile: Dockerfile
      args:
        JWT_SECRET: ${JWT_SECRET}
        DATA_FOLDER: "/data/"
    hostname: webftp
    expose:
      - 8000
    volumes:
      - "/home/mchost/servers:/data"
    environment:
      ROCKET_DATABASES: '{theuntitledcloud={url="postgres://${DATABASE_USER}:${DATABASE_PASS}@database:5432/${DATABASE_NAME}"}}'
    networks:
      mc_host_network:
    depends_on:
      - mc_host_database

networks:
  mc_host_network:
  internal:
    driver: bridge
    internal: true
