volumes:
  data:

networks:
  app:

services:
  postgres:
    image: postgres:latest
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
    networks:
      app:

  ftp:
    build: .
    ports:
      - 21:21
      - 20:20
      - 1024-1048:1024-1048
    depends_on:
      - postgres
    volumes:
      - "./data:/data"
    networks:
      app:
    env_file:
      - .env