volumes:
  data:

networks:
  app:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
    networks:
      app:
        ipv4_address: 10.5.0.5
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]

  myapp:
    build: .
    networks:
      app:
        ipv4_address: 10.5.0.6
    ports:
      - 21:21
      - 20:20
      - 1024-1048:1024-1048
    depends_on:
      - postgres