version: "3.8"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "55000:5432"
    restart: unless-stopped