import type { SelectItem } from "$components/select/SelectItem";

export const games: SelectItem[] = [
	{value: "acserver", label: "Assetto Corsa"},
	{value: "ahlserver", label: "Action Half-Life"},
	{value: "ahl2server", label: "Action: Source"},
	{value: "arkserver", label: "ARK: Survival Evolved"},
	{value: "arma3server", label: "ARMA 3"},
	{value: "armarserver", label: "Arma Reforger"},
	{value: "avserver", label: "Avorion"},
	{value: "bbserver", label: "BrainBread"},
	{value: "bb2server", label: "BrainBread 2"},
	{value: "bdserver", label: "Base Defense"},
	{value: "bf1942server", label: "Battlefield 1942"},
	{value: "bfvserver", label: "Battlefield: Vietnam"},
	{value: "bmdmserver", label: "Black Mesa: Deathmatch"},
	{value: "boserver", label: "Ballistic Overkill"},
	{value: "bsserver", label: "Blade Symphony"},
	{value: "btserver", label: "Barotrauma"},
	{value: "bt1944server", label: "Battalion 1944"},
	{value: "ccserver", label: "Codename CURE"},
	{value: "cdserver", label: "Crafting Dead"},
	{value: "cmwserver", label: "Chivalry: Medieval Warfare"},
	{value: "codserver", label: "Call of Duty"},
	{value: "cod2server", label: "Call of Duty 2"},
	{value: "cod4server", label: "Call of Duty 4"},
	{value: "coduoserver", label: "Call of Duty: United Offensive"},
	{value: "codwawserver", label: "Call of Duty: World at War"},
	{value: "colserver", label: "Colony Survival"},
	{value: "csserver", label: "Counter-Strike 1.6"},
	{value: "csczserver", label: "Counter-Strike: Condition Zero"},
	{value: "csgoserver", label: "Counter-Strike: Global Offensive"},
	{value: "cssserver", label: "Counter-Strike: Source"},
	{value: "dabserver", label: "Double Action: Boogaloo"},
	{value: "dayzserver", label: "DayZ"},
	{value: "dmcserver", label: "Deathmatch Classic"},
	{value: "dodserver", label: "Day of Defeat"},
	{value: "dodrserver", label: "Day of Dragons"},
	{value: "dodsserver", label: "Day of Defeat: Source"},
	{value: "doiserver", label: "Day of Infamy"},
	{value: "dstserver", label: "Don't Starve Together"},
	{value: "dysserver", label: "Dystopia"},
	{value: "ecoserver", label: "Eco"},
	{value: "emserver", label: "Empires Mod"},
	{value: "etlserver", label: "ET: Legacy"},
	{value: "fctrserver", label: "Factorio"},
	{value: "fofserver", label: "Fistful of Frags"},
	{value: "gmodserver", label: "Garrys Mod"},
	{value: "hl2dmserver", label: "Half-Life 2: Deathmatch"},
	{value: "hldmserver", label: "Half-Life: Deathmatch"},
	{value: "hldmsserver", label: "Half-Life Deathmatch: Source"},
	{value: "hwserver", label: "Hurtworld"},
	{value: "insserver", label: "Insurgency"},
	{value: "inssserver", label: "Insurgency: Sandstorm"},
	{value: "iosserver", label: "IOSoccer"},
	{value: "jc2server", label: "Just Cause 2"},
	{value: "jc3server", label: "Just Cause 3"},
	{value: "jk2server", label: "Jedi Knight II: Jedi Outcast"},
	{value: "kfserver", label: "Killing Floor"},
	{value: "kf2server", label: "Killing Floor 2"},
	{value: "loserver", label: "Last Oasis"},
	{value: "l4dserver", label: "Left 4 Dead"},
	{value: "l4d2server", label: "Left 4 Dead 2"},
	{value: "mcserver", label: "Minecraft"},
	{value: "mcbserver", label: "Minecraft Bedrock"},
	{value: "mhserver", label: "MORDHAU"},
	{value: "mohaaserver", label: "Medal of Honor: Allied Assault"},
	{value: "momserver", label: "Memories of Mars"},
	{value: "mtaserver", label: "Multi Theft Auto"},
	{value: "mumbleserver", label: "Mumble"},
	{value: "ndserver", label: "Nuclear Dawn"},
	{value: "nmrihserver", label: "No More Room in Hell"},
	{value: "nsserver", label: "Natural Selection"},
	{value: "ns2server", label: "Natural Selection 2"},
	{value: "ns2cserver", label: "NS2: Combat"},
	{value: "onsetserver", label: "Onset"},
	{value: "opforserver", label: "Opposing Force"},
	{value: "pcserver", label: "Project Cars"},
	{value: "pc2server", label: "Project Cars 2"},
	{value: "pmcserver", label: "PaperMC"},
	{value: "pstbsserver", label: "Post Scriptum: The Bloody Seventh"},
	{value: "pvkiiserver", label: "Pirates Vikings & Knights II"},
	{value: "pvrserver", label: "Pavlov VR"},
	{value: "pzserver", label: "Project Zomboid"},
	{value: "q2server", label: "Quake 2"},
	{value: "q3server", label: "Quake 3: Arena"},
	{value: "qlserver", label: "Quake Live"},
	{value: "qwserver", label: "Quake World"},
	{value: "ricochetserver", label: "Ricochet"},
	{value: "roserver", label: "Red Orchestra: Ostfront 41-45"},
	{value: "rtcwserver", label: "Return to Castle Wolfenstein"},
	{value: "rustserver", label: "Rust"},
	{value: "rwserver", label: "Rising World"},
	{value: "sampserver", label: "San Andreas Multiplayer"},
	{value: "sbserver", label: "Starbound"},
	{value: "sbotsserver", label: "StickyBots"},
	{value: "scpslserver", label: "SCP: Secret Laboratory"},
	{value: "scpslsmserver", label: "SCP: Secret Laboratory ServerMod"},
	{value: "sdtdserver", label: "7 Days to Die"},
	{value: "sfcserver", label: "SourceForts Classic"},
	{value: "sfserver", label: "Satisfactory"},
	{value: "sof2server", label: "Soldier Of Fortune 2: Gold Edition"},
	{value: "solserver", label: "Soldat"},
	{value: "squadserver", label: "Squad"},
	{value: "stserver", label: "Stationeers"},
	{value: "stnserver", label: "Survive the Nights"},
	{value: "svenserver", label: "Sven Co-op"},
	{value: "terrariaserver", label: "Terraria"},
	{value: "tf2server", label: "Team Fortress 2"},
	{value: "tfcserver", label: "Team Fortress Classic"},
	{value: "tiserver", label: "The Isle"},
	{value: "tsserver", label: "The Specialists"},
	{value: "ts3server", label: "Teamspeak 3"},
	{value: "tuserver", label: "Tower Unite"},
	{value: "twserver", label: "Teeworlds"},
	{value: "untserver", label: "Unturned"},
	{value: "utserver", label: "Unreal Tournament"},
	{value: "ut2k4server", label: "Unreal Tournament 2004"},
	{value: "ut3server", label: "Unreal Tournament 3"},
	{value: "ut99server", label: "Unreal Tournament 99"},
	{value: "vhserver", label: "Valheim"},
	{value: "vintsserver", label: "Vintage Story"},
	{value: "vsserver", label: "Vampire Slayer"},
	{value: "wetserver", label: "Wolfenstein: Enemy Territory"},
	{value: "wfserver", label: "Warfork"},
	{value: "wmcserver", label: "WaterfallMC"},
	{value: "wurmserver", label: "Wurm Unlimited"},
	{value: "zmrserver", label: "Zombie Master: Reborn"},
	{value: "zpsserver", label: "Zombie Panic! Source"},
];
