package dev.quozul.servers.helpers

class NameGenerator {
	companion object {
		private val left = listOf(
			"admiring",
			"adoring",
			"agitated",
			"amazing",
			"angry",
			"awesome",
			"backstabbing",
			"berserk",
			"big",
			"boring",
			"clever",
			"cocky",
			"compassionate",
			"condescending",
			"cranky",
			"desperate",
			"determined",
			"distracted",
			"dreamy",
			"drunk",
			"ecstatic",
			"elated",
			"elegant",
			"evil",
			"fervent",
			"focused",
			"furious",
			"gigantic",
			"gloomy",
			"goofy",
			"grave",
			"happy",
			"high",
			"hopeful",
			"hungry",
			"insane",
			"jolly",
			"jovial",
			"kickass",
			"lonely",
			"loving",
			"mad",
			"modest",
			"naughty",
			"nauseous",
			"nostalgic",
			"pedantic",
			"pensive",
			"prickly",
			"reverent",
			"romantic",
			"sad",
			"serene",
			"sharp",
			"sick",
			"silly",
			"sleepy",
			"small",
			"stoic",
			"stupefied",
			"suspicious",
			"tender",
			"thirsty",
			"tiny",
			"trusting",
		)
		private val right = listOf(
			"allay",
			"armor stand",
			"arrow",
			"axolotl",
			"bat",
			"bee",
			"blaze",
			"boat",
			"boat with chest",
			"cat",
			"cave spider",
			"minecart with chest",
			"chicken",
			"minecart with command block",
			"cod",
			"cow",
			"creeper",
			"dolphin",
			"donkey",
			"drowned",
			"dragon fireball",
			"egg",
			"elder guardian",
			"end crystal",
			"ender dragon",
			"ender pearl",
			"enderman",
			"endermite",
			"evoker fangs",
			"evoker",
			"eye of ender",
			"falling block",
			"fireball",
			"firework rocket",
			"fishing bobber",
			"fox",
			"frog",
			"minecart with furnace",
			"ghast",
			"giant",
			"glow item frame",
			"glow squid",
			"goat",
			"guardian",
			"hoglin",
			"minecart with hopper",
			"horse",
			"husk",
			"ravager",
			"illusioner",
			"item",
			"item frame",
			"the killer bunny",
			"leash knot",
			"lightning bolt",
			"llama",
			"llama spit",
			"magma cube",
			"marker",
			"minecart",
			"mooshroom",
			"mule",
			"ocelot",
			"painting",
			"panda",
			"parrot",
			"phantom",
			"pig",
			"piglin",
			"piglin brute",
			"pillager",
			"player",
			"polar bear",
			"potion",
			"pufferfish",
			"rabbit",
			"salmon",
			"sheep",
			"shulker",
			"shulker bullet",
			"silverfish",
			"skeleton",
			"skeleton horse",
			"slime",
			"small fireball",
			"snowball",
			"snow golem",
			"minecart with spawner",
			"spectral arrow",
			"spider",
			"squid",
			"stray",
			"strider",
			"tadpole",
			"primed tnt",
			"minecart with tnt",
			"trader llama",
			"trident",
			"tropical fish",
			"anemone",
			"black tang",
			"blue tang",
			"butterflyfish",
			"cichlid",
			"clownfish",
			"cotton candy betta",
			"dottyback",
			"emperor red snapper",
			"goatfish",
			"moorish idol",
			"ornate butterflyfish",
			"parrotfish",
			"queen angelfish",
			"red cichlid",
			"red lipped blenny",
			"red snapper",
			"threadfin",
			"tomato clownfish",
			"triggerfish",
			"yellowtail parrotfish",
			"yellow tang",
			"flopper",
			"stripey",
			"glitter",
			"blockfish",
			"betty",
			"clayfish",
			"kob",
			"sunstreak",
			"snooper",
			"dasher",
			"brinely",
			"spotty",
			"turtle",
			"vex",
			"armorer",
			"butcher",
			"cartographer",
			"cleric",
			"farmer",
			"fisherman",
			"fletcher",
			"leatherworker",
			"librarian",
			"mason",
			"villager",
			"nitwit",
			"shepherd",
			"toolsmith",
			"weaponsmith",
			"villager",
			"wandering trader",
			"iron golem",
			"vindicator",
			"warden",
			"witch",
			"wither",
			"wither skeleton",
			"wither skull",
			"wolf",
			"bottle o' enchanting",
			"experience orb",
			"zoglin",
			"zombie",
			"zombie horse",
			"zombified piglin",
			"zombie villager",
		)

		fun getRandomName(): String {
			return "${left.random()} ${right.random()}"
		}
	}
}