version: "3.8"
services:
  postgres:
    image: postgres:14-alpine
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "55000:5432"
    expose:
      - 5432
    restart: unless-stopped
    command: [ "postgres", "-c", "log_statement=all" ]
    networks:
      dev-database:

networks:
  dev-database:
    driver: bridge